version: '3'

services:
  psql:
    image: postgres:11-alpine
    command: '-c max_connections=500'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 25432:5432
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pusher:
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=psql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: pusher:${VERSION}
    command: ["/apps/pusher/bin/pusher", "-port 8080", "-pushover_app_token=${PUSHOVER_APP_TOKEN}", "-pushover_user_token=${PUSHOVER_USER_TOKEN}", "-log_file /apps/pusher/pusher_log.log"]
    ports:
      - 8888:8080
    depends_on:
      - psql
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./pusher_log.log:/apps/pusher/pusher_log.log
